In [2]:
import torch

t1 = torch.tensor([
    [23, 45, 23],
    [3, 45, 2]
])

t2 = torch.tensor([
    [23, 5],
    [3, 4],
    [5, 45]
])


In [3]:
t1

tensor([[23, 45, 23],
        [ 3, 45,  2]])

In [4]:
t1.T

tensor([[23,  3],
        [45, 45],
        [23,  2]])

In [5]:
torch.matmul(t1, t2)

tensor([[ 779, 1330],
        [ 214,  285]])

In [6]:
data = torch.rand(1000, 3)

In [7]:
# first 10 records
data[:10]

tensor([[0.0383, 0.0719, 0.1797],
        [0.4073, 0.1281, 0.5247],
        [0.3826, 0.1927, 0.0523],
        [0.1165, 0.1327, 0.3985],
        [0.5005, 0.8555, 0.0509],
        [0.2568, 0.3207, 0.6814],
        [0.5130, 0.8661, 0.8048],
        [0.6214, 0.9216, 0.1694],
        [0.1192, 0.9011, 0.5544],
        [0.7933, 0.3990, 0.1676]])

In [8]:
index = data[:, 1]>0.5  #  all data where column 1(starts is 0) > 0.5
data[index]

tensor([[0.5005, 0.8555, 0.0509],
        [0.5130, 0.8661, 0.8048],
        [0.6214, 0.9216, 0.1694],
        ...,
        [0.4742, 0.6106, 0.8710],
        [0.2018, 0.7326, 0.6623],
        [0.6773, 0.5668, 0.8786]])

In [9]:
# Derivaties
data

tensor([[0.0383, 0.0719, 0.1797],
        [0.4073, 0.1281, 0.5247],
        [0.3826, 0.1927, 0.0523],
        ...,
        [0.2018, 0.7326, 0.6623],
        [0.6773, 0.5668, 0.8786],
        [0.9955, 0.1020, 0.6646]])

In [17]:
x = torch.tensor([1.0, 2.0, 3.5],requires_grad=True)
y = torch.tensor([1.9, 2.89, 3.9],requires_grad=True)
z = x*2 + y**3 # Equation 
z.sum().backward() # For backward propagation value must be scalar; To get the grad values  we need to do backward (backward propagetion)

In [18]:
x.grad

tensor([2., 2., 2.])

In [19]:
y.grad

tensor([10.8300, 25.0563, 45.6300])